version: "3.11"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - CONNECTION_STRING=mongodb://dev:password@mongodb:27017/
    volumes:
      - type: bind
        source: ./todo_app
        target: /app/todo_app
    depends_on:
      - mongodb
      - prometheus
  
  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "5000:5000"
    env_file:
      - .env
    
  prometheus:
    image: prom/prometheus
    ports: 
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    env_file:
      - .env.test
  
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: todoapp-db