version: "3"

services:

  todoapp:
    build:
      context: ./
      dockerfile: Dockerfile
      target: ${BUILD_TARGET}
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: .
        target: /app