name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'documentation/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'documentation/**'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: touch .env
      - run: docker compose up test --build
  
  deploy:
    name: Build and deploy to DockerHub
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to DockerHub
        uses: actions/checkout@v2
      - name: Build and push production image
        run: docker build --target production --tag bogdanradulescu97/todo-app-production-image:latest .
      - name: Publish production image
        run: docker push bogdanradulescu97/todo-app-production-image:latest
      - name: Pull image to Azure App Service
        run: curl -dH -X POST '${{ secrets.APP_SERVICE_WEBHOOK }}'