name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'documentation/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'documentation/**'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build --target test --tag todo-app-test-image .
      - run: docker run -e SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }} -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} -e COLLECTION_NAME=${{ secrets.COLLECTION_NAME }} -e CONNECTION_STRING=mongodb://fakemongo.com todo-app-test-image
  
  deploy:
    name: Build and deploy to DockerHub
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref_name == 'module-10'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to DockerHub
        uses: actions/checkout@v2
      - name: Build and push production image
        run: docker build --target production --tag bogdanradulescu97/todo-app-production-image:latest .
      - name: Publish production image
        run: docker push bogdanradulescu97/todo-app-production-image:latest