name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'documentation/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'documentation/**'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build --target test --tag todo-app-test-image .
      - run: docker run -e SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }} -e TRELLO_CONSUMER_KEY=${{ secrets.TRELLO_CONSUMER_KEY }} -e TRELLO_CONSUMER_SECRET=${{ secrets.TRELLO_CONSUMER_SECRET }} -e TRELLO_ACCESS_TOKEN=${{ secrets.TRELLO_ACCESS_TOKEN }} -e TRELLO_BOARD_ID=${{ secrets.TRELLO_BOARD_ID }} todo-app-test-image
  
  deploy:
    name: Deploy to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the image
        run: echo Publishing
        if: ${{ github.event_name == "push" && github.ref_name == "module8" }}
    needs: build